name: 'Read package.json version (and other properties)'
description: 'Output version numbers (and other properties) from package.json'
inputs:
  path:
    description: 'Path of package.json'
    default: "./"
  propertyKey:
    description: 'Property name to read from package.json'
    default: "version"
outputs:
  propertyValue:
    description: "Version or other properties of package.json"
runs:
  using: 'node12'
  main: 'dist/index.js'
